export const img_paths = {
  fractions: {
    adept_f: () => `/adept_f.jpg`,
    adept_m: () => `/adept_m.jpg`,
    novice_f: () => `/novice_f.jpg`,
    novice_m: () => `/novice_m.jpg`,
  },
  mining_cave: () => `/mining_cave.jpg`,
  meditation: () => `/meditation.jpg`,
  spirit_path: () => `/spirit_path.jpg`,
  facts: () => `/facts.jpg`,
  home: () => `/home.jpg`,
  temple: () => `/temple.jpg`,
  fight: () => `/fight.jpg`,
  fight_list: {
    demonic_beast: () => `/demonic_beast.jpg`,
  },
  mission: () => `/missions.jpg`,
  qi_skills: () => `/qi_skills.jpg`,
  qi_skills_list: {
    qi_veil: () => `/qi_veil.jpg`,
    seal_of_mind: () => `/seal_of_mind.jpg`,
    circulation_of_life: () => `/circulation_of_life.jpg`,
    spatial_vault: () => `/spatial_vault.jpg`,
  },
  params_training: {
    power: () => `/power.png`,
    protection: () => `/protection.png`,
    speed: () => `/speed.png`,
    skill: () => `/skill.png`,
    qi_param: () => `/qi_param.png`,
    max_hp: () => `/max_hp.png`,
  },
  ranking_page: () => `/ranking.jpg`,
};
