-- AlterTable
ALTER TABLE "user_daily_stats" ADD COLUMN     "glory" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "missions" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "qi_looted" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "qi_lost" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "qi_stone_looted" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "qi_stone_lost" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "user_statistics" ADD COLUMN     "glory" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "missions" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "qi_looted" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "qi_lost" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "qi_stone_looted" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "qi_stone_lost" INTEGER NOT NULL DEFAULT 0;
